plugins {
    id 'com.android.application'
}

android {
    namespace 'com.dataroda.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.dataroda.app"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
}
