name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Zip File
        run: |
          mkdir data-roda-app
          cp indeks.html data-roda-app/index.html || cp index.html data-roda-app/index.html
          zip -r data-roda-app.zip data-roda-app

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: data-roda-app
          path: data-roda-app.zip
